// Code generated by goyacc -p YY -o parser/parser.go -v parser/parser.output parser/grammar.y. DO NOT EDIT.

//line parser/grammar.y:2
package parser

import __yyfmt__ "fmt"

//line parser/grammar.y:2

//line parser/grammar.y:6
type YYSymType struct {
	yys    int
	String string
	Ast    Ast
	Asts   []Ast
	Params []Param
	Type   Type
}

const NUMBER = 57346
const IDENTIFIER = 57347
const SEPARATOR = 57348
const ASSIGN = 57349
const LET = 57350
const IF = 57351
const LT = 57352
const LTE = 57353
const GT = 57354
const GTE = 57355
const EQ = 57356
const NE = 57357
const OR = 57358
const AND = 57359
const ELSE = 57360
const WHILE = 57361
const PRINT = 57362
const FUNC = 57363
const RETURN = 57364
const TYPE_INT = 57365
const TYPE_DOUBLE = 57366
const TYPE_BOOL = 57367
const TYPE_VOID = 57368
const TRUE = 57369
const FALSE = 57370
const NO_ELSE = 57371
const UMINUS = 57372

var YYToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMBER",
	"IDENTIFIER",
	"SEPARATOR",
	"ASSIGN",
	"LET",
	"IF",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"EQ",
	"NE",
	"OR",
	"AND",
	"ELSE",
	"WHILE",
	"PRINT",
	"FUNC",
	"RETURN",
	"TYPE_INT",
	"TYPE_DOUBLE",
	"TYPE_BOOL",
	"TYPE_VOID",
	"TRUE",
	"FALSE",
	"NO_ELSE",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"UMINUS",
	"'('",
	"')'",
	"':'",
	"'{'",
	"'}'",
	"','",
}

var YYStatenames = [...]string{}

const YYEofCode = 1
const YYErrCode = 2
const YYInitialStackSize = 16

//line parser/grammar.y:139

//line yacctab:1
var YYExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const YYPrivate = 57344

const YYLast = 261

var YYAct = [...]int8{
	96, 4, 78, 86, 77, 113, 111, 105, 103, 110,
	106, 91, 90, 102, 92, 12, 44, 87, 43, 45,
	69, 85, 48, 76, 41, 42, 51, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 61, 62, 13, 14,
	63, 50, 17, 66, 67, 49, 16, 47, 108, 70,
	89, 71, 72, 41, 28, 30, 29, 31, 32, 33,
	34, 35, 28, 30, 29, 31, 32, 33, 34, 35,
	24, 25, 26, 27, 24, 25, 26, 27, 39, 88,
	84, 38, 24, 25, 26, 27, 26, 27, 83, 37,
	94, 95, 98, 36, 93, 100, 75, 46, 104, 79,
	80, 81, 101, 40, 97, 107, 2, 109, 79, 80,
	81, 112, 28, 30, 29, 31, 32, 33, 34, 35,
	28, 30, 29, 31, 32, 33, 34, 35, 99, 74,
	73, 65, 24, 25, 26, 27, 64, 8, 82, 3,
	24, 25, 26, 27, 12, 15, 68, 10, 18, 21,
	9, 7, 6, 5, 1, 0, 0, 0, 0, 22,
	19, 11, 20, 0, 0, 12, 15, 13, 14, 18,
	21, 17, 0, 0, 0, 16, 0, 0, 0, 0,
	22, 19, 0, 20, 0, 0, 0, 0, 13, 14,
	0, 0, 17, 23, 0, 0, 16, 28, 30, 29,
	31, 32, 33, 34, 35, 28, 30, 29, 31, 32,
	33, 34, 35, 0, 0, 0, 0, 24, 25, 26,
	27, 0, 0, 0, 0, 24, 25, 26, 27, 28,
	30, 29, 31, 32, 33, 0, 35, 28, 30, 29,
	31, 32, 33, 0, 0, 0, 0, 0, 0, 24,
	25, 26, 27, 0, 0, 0, 0, 24, 25, 26,
	27,
}

var YYPact = [...]int16{
	-32768, 140, -32768, -32768, 187, 87, 83, 75, 72, -32768,
	-32768, 98, -32768, -32768, -32768, 18, 11, 11, 92, 12,
	11, 10, 6, -32768, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, -32768, -32768, -32768, -32768,
	5, 11, 11, 110, -11, -32768, -17, 11, 195, 11,
	11, 54, 54, -32768, -32768, 40, 40, 40, 40, 40,
	40, 219, 227, 91, -13, -36, 195, 195, -32768, 85,
	102, 52, 44, -15, -37, -20, -32768, 11, 43, -32768,
	-32768, -32768, -32768, -26, -27, -23, 89, 85, 195, 11,
	161, 161, 76, -24, -32768, 195, -31, 161, -32, -28,
	-32768, -32768, 85, 30, -32768, -32768, 161, -32768, -29, -33,
	161, -32768, -34, -32768,
}

var YYPgo = [...]uint8{
	0, 154, 0, 104, 1, 153, 152, 151, 150, 147,
	139, 137, 136, 131, 130, 129, 2, 128,
}

var YYR1 = [...]int8{
	0, 1, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 2, 2, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 16, 16, 16, 17, 17, 5, 6, 7,
	8, 8, 9, 10, 14, 14, 15, 15, 11, 11,
	12, 12, 13, 13,
}

var YYR2 = [...]int8{
	0, 0, 2, 2, 2, 2, 2, 2, 2, 1,
	1, 2, 1, 1, 1, 1, 1, 4, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 1, 1, 1, 1, 1, 6, 3, 4,
	7, 11, 7, 10, 0, 1, 3, 5, 2, 1,
	0, 1, 1, 3,
}

var YYChk = [...]int16{
	-32768, -1, -3, -10, -4, -5, -6, -7, -11, -8,
	-9, 21, 4, 27, 28, 5, 35, 31, 8, 20,
	22, 9, 19, 6, 30, 31, 32, 33, 10, 12,
	11, 13, 14, 15, 16, 17, 6, 6, 6, 6,
	5, 35, 7, -4, 5, -4, 5, 35, -4, 35,
	35, -4, -4, -4, -4, -4, -4, -4, -4, -4,
	-4, -4, -4, 35, -12, -13, -4, -4, 36, 37,
	-4, -4, -4, -14, -15, 5, 36, 40, -16, 23,
	24, 25, 36, 36, 36, 36, 40, 37, -4, 7,
	38, 38, 37, 5, -16, -4, -2, -3, -2, -17,
	-16, 26, 37, 39, -2, 39, 38, -16, 18, -2,
	38, 39, -2, 39,
}

var YYDef = [...]int8{
	1, -2, 2, 3, 0, 0, 0, 0, 0, 9,
	10, 0, 13, 14, 15, 16, 0, 0, 0, 0,
	49, 0, 0, 4, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 5, 6, 7, 8,
	0, 50, 0, 0, 16, 31, 0, 0, 48, 0,
	0, 18, 19, 20, 21, 22, 23, 24, 25, 26,
	27, 28, 29, 44, 0, 51, 52, 38, 30, 0,
	0, 0, 0, 0, 45, 0, 17, 0, 0, 32,
	33, 34, 39, 0, 0, 0, 0, 0, 53, 0,
	0, 0, 0, 0, 46, 37, 0, 12, 0, 0,
	35, 36, 0, 40, 11, 42, 0, 47, 0, 0,
	0, 43, 0, 41,
}

var YYTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	35, 36, 32, 30, 40, 31, 3, 33, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 37, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 38, 3, 39,
}

var YYTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 34,
}

var YYTok3 = [...]int8{
	0,
}

var YYErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	YYDebug        = 0
	YYErrorVerbose = false
)

type YYLexer interface {
	Lex(lval *YYSymType) int
	Error(s string)
}

type YYParser interface {
	Parse(YYLexer) int
	Lookahead() int
}

type YYParserImpl struct {
	lval  YYSymType
	stack [YYInitialStackSize]YYSymType
	char  int
}

func (p *YYParserImpl) Lookahead() int {
	return p.char
}

func YYNewParser() YYParser {
	return &YYParserImpl{}
}

const YYFlag = -32768

func YYTokname(c int) string {
	if c >= 1 && c-1 < len(YYToknames) {
		if YYToknames[c-1] != "" {
			return YYToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func YYStatname(s int) string {
	if s >= 0 && s < len(YYStatenames) {
		if YYStatenames[s] != "" {
			return YYStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func YYErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !YYErrorVerbose {
		return "syntax error"
	}

	for _, e := range YYErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + YYTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(YYPact[state])
	for tok := TOKSTART; tok-1 < len(YYToknames); tok++ {
		if n := base + tok; n >= 0 && n < YYLast && int(YYChk[int(YYAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if YYDef[state] == -2 {
		i := 0
		for YYExca[i] != -1 || int(YYExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; YYExca[i] >= 0; i += 2 {
			tok := int(YYExca[i])
			if tok < TOKSTART || YYExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if YYExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += YYTokname(tok)
	}
	return res
}

func YYlex1(lex YYLexer, lval *YYSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(YYTok1[0])
		goto out
	}
	if char < len(YYTok1) {
		token = int(YYTok1[char])
		goto out
	}
	if char >= YYPrivate {
		if char < YYPrivate+len(YYTok2) {
			token = int(YYTok2[char-YYPrivate])
			goto out
		}
	}
	for i := 0; i < len(YYTok3); i += 2 {
		token = int(YYTok3[i+0])
		if token == char {
			token = int(YYTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(YYTok2[1]) /* unknown char */
	}
	if YYDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", YYTokname(token), uint(char))
	}
	return char, token
}

func YYParse(YYlex YYLexer) int {
	return YYNewParser().Parse(YYlex)
}

func (YYrcvr *YYParserImpl) Parse(YYlex YYLexer) int {
	var YYn int
	var YYVAL YYSymType
	var YYDollar []YYSymType
	_ = YYDollar // silence set and not used
	YYS := YYrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	YYstate := 0
	YYrcvr.char = -1
	YYtoken := -1 // YYrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		YYstate = -1
		YYrcvr.char = -1
		YYtoken = -1
	}()
	YYp := -1
	goto YYstack

ret0:
	return 0

ret1:
	return 1

YYstack:
	/* put a state and value onto the stack */
	if YYDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", YYTokname(YYtoken), YYStatname(YYstate))
	}

	YYp++
	if YYp >= len(YYS) {
		nyys := make([]YYSymType, len(YYS)*2)
		copy(nyys, YYS)
		YYS = nyys
	}
	YYS[YYp] = YYVAL
	YYS[YYp].yys = YYstate

YYnewstate:
	YYn = int(YYPact[YYstate])
	if YYn <= YYFlag {
		goto YYdefault /* simple state */
	}
	if YYrcvr.char < 0 {
		YYrcvr.char, YYtoken = YYlex1(YYlex, &YYrcvr.lval)
	}
	YYn += YYtoken
	if YYn < 0 || YYn >= YYLast {
		goto YYdefault
	}
	YYn = int(YYAct[YYn])
	if int(YYChk[YYn]) == YYtoken { /* valid shift */
		YYrcvr.char = -1
		YYtoken = -1
		YYVAL = YYrcvr.lval
		YYstate = YYn
		if Errflag > 0 {
			Errflag--
		}
		goto YYstack
	}

YYdefault:
	/* default state action */
	YYn = int(YYDef[YYstate])
	if YYn == -2 {
		if YYrcvr.char < 0 {
			YYrcvr.char, YYtoken = YYlex1(YYlex, &YYrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if YYExca[xi+0] == -1 && int(YYExca[xi+1]) == YYstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			YYn = int(YYExca[xi+0])
			if YYn < 0 || YYn == YYtoken {
				break
			}
		}
		YYn = int(YYExca[xi+1])
		if YYn < 0 {
			goto ret0
		}
	}
	if YYn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			YYlex.Error(YYErrorMessage(YYstate, YYtoken))
			Nerrs++
			if YYDebug >= 1 {
				__yyfmt__.Printf("%s", YYStatname(YYstate))
				__yyfmt__.Printf(" saw %s\n", YYTokname(YYtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for YYp >= 0 {
				YYn = int(YYPact[YYS[YYp].yys]) + YYErrCode
				if YYn >= 0 && YYn < YYLast {
					YYstate = int(YYAct[YYn]) /* simulate a shift of "error" */
					if int(YYChk[YYstate]) == YYErrCode {
						goto YYstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if YYDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", YYS[YYp].yys)
				}
				YYp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if YYDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", YYTokname(YYtoken))
			}
			if YYtoken == YYEofCode {
				goto ret1
			}
			YYrcvr.char = -1
			YYtoken = -1
			goto YYnewstate /* try again in the same state */
		}
	}

	/* reduction by production YYn */
	if YYDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", YYn, YYStatname(YYstate))
	}

	YYnt := YYn
	YYpt := YYp
	_ = YYpt // guard against "declared and not used"

	YYp -= int(YYR2[YYn])
	// YYp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if YYp+1 >= len(YYS) {
		nyys := make([]YYSymType, len(YYS)*2)
		copy(nyys, YYS)
		YYS = nyys
	}
	YYVAL = YYS[YYp+1]

	/* consult goto table to find next state */
	YYn = int(YYR1[YYn])
	YYg := int(YYPgo[YYn])
	YYj := YYg + YYS[YYp].yys + 1

	if YYj >= YYLast {
		YYstate = int(YYAct[YYg])
	} else {
		YYstate = int(YYAct[YYj])
		if int(YYChk[YYstate]) != -YYn {
			YYstate = int(YYAct[YYg])
		}
	}
	// dummy call; replaced with literal code
	switch YYnt {

	case 1:
		YYDollar = YYS[YYpt-0 : YYpt+1]
//line parser/grammar.y:36
		{
			root := &Block{}
			YYVAL.Ast = root
			YYlex.(*Lexer).rootAst = root
		}
	case 2:
		YYDollar = YYS[YYpt-2 : YYpt+1]
//line parser/grammar.y:37
		{
			blk := YYDollar[1].Ast.(*Block)
			blk.Stmts = append(blk.Stmts, YYDollar[2].Ast)
			YYVAL.Ast = blk
		}
	case 3:
		YYDollar = YYS[YYpt-2 : YYpt+1]
//line parser/grammar.y:38
		{
			blk := YYDollar[1].Ast.(*Block)
			blk.Stmts = append(blk.Stmts, YYDollar[2].Ast)
			YYVAL.Ast = blk
		}
	case 11:
		YYDollar = YYS[YYpt-2 : YYpt+1]
//line parser/grammar.y:52
		{
			blk := YYDollar[2].Ast.(*Block)
			blk.Stmts = append([]Ast{YYDollar[1].Ast}, blk.Stmts...)
			YYVAL.Ast = blk
		}
	case 12:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:53
		{
			YYVAL.Ast = &Block{Stmts: []Ast{YYDollar[1].Ast}}
		}
	case 13:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:57
		{
			YYVAL.Ast = newNumber(YYDollar[1].String)
		}
	case 14:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:58
		{
			YYVAL.Ast = &BoolLit{Value: true}
		}
	case 15:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:59
		{
			YYVAL.Ast = &BoolLit{Value: false}
		}
	case 16:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:60
		{
			YYVAL.Ast = &Variable{YYDollar[1].String}
		}
	case 17:
		YYDollar = YYS[YYpt-4 : YYpt+1]
//line parser/grammar.y:61
		{
			YYVAL.Ast = &CallExpr{Name: YYDollar[1].String, Args: YYDollar[3].Asts}
		}
	case 18:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:62
		{
			YYVAL.Ast = &BinaryExpr{Op: "+", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 19:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:63
		{
			YYVAL.Ast = &BinaryExpr{Op: "-", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 20:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:64
		{
			YYVAL.Ast = &BinaryExpr{Op: "*", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 21:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:65
		{
			YYVAL.Ast = &BinaryExpr{Op: "/", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 22:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:66
		{
			YYVAL.Ast = &BinaryExpr{Op: "<", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 23:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:67
		{
			YYVAL.Ast = &BinaryExpr{Op: ">", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 24:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:68
		{
			YYVAL.Ast = &BinaryExpr{Op: "<=", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 25:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:69
		{
			YYVAL.Ast = &BinaryExpr{Op: ">=", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 26:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:70
		{
			YYVAL.Ast = &BinaryExpr{Op: "==", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 27:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:71
		{
			YYVAL.Ast = &BinaryExpr{Op: "!=", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 28:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:72
		{
			YYVAL.Ast = &BinaryExpr{Op: "||", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 29:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:73
		{
			YYVAL.Ast = &BinaryExpr{Op: "&&", Lhs: YYDollar[1].Ast, Rhs: YYDollar[3].Ast}
		}
	case 30:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:74
		{
			YYVAL.Ast = &ParenExpr{YYDollar[2].Ast}
		}
	case 31:
		YYDollar = YYS[YYpt-2 : YYpt+1]
//line parser/grammar.y:75
		{
			YYVAL.Ast = &UnaryExpr{YYDollar[2].Ast}
		}
	case 32:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:79
		{
			YYVAL.Type = TypeInt
		}
	case 33:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:80
		{
			YYVAL.Type = TypeDouble
		}
	case 34:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:81
		{
			YYVAL.Type = TypeBool
		}
	case 35:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:85
		{
			YYVAL.Type = YYDollar[1].Type
		}
	case 36:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:86
		{
			YYVAL.Type = TypeVoid
		}
	case 37:
		YYDollar = YYS[YYpt-6 : YYpt+1]
//line parser/grammar.y:90
		{
			YYVAL.Ast = &Assignment{Variable: YYDollar[2].String, Type: YYDollar[4].Type, Expr: YYDollar[6].Ast}
		}
	case 38:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:94
		{
			YYVAL.Ast = &Reassignment{Variable: YYDollar[1].String, Expr: YYDollar[3].Ast}
		}
	case 39:
		YYDollar = YYS[YYpt-4 : YYpt+1]
//line parser/grammar.y:98
		{
			YYVAL.Ast = &StdPrint{Expr: YYDollar[3].Ast}
		}
	case 40:
		YYDollar = YYS[YYpt-7 : YYpt+1]
//line parser/grammar.y:102
		{
			YYVAL.Ast = &IfStatement{Cond: YYDollar[3].Ast, ThenStmt: YYDollar[6].Ast, ElseStmt: nil}
		}
	case 41:
		YYDollar = YYS[YYpt-11 : YYpt+1]
//line parser/grammar.y:103
		{
			YYVAL.Ast = &IfStatement{Cond: YYDollar[3].Ast, ThenStmt: YYDollar[6].Ast, ElseStmt: YYDollar[10].Ast}
		}
	case 42:
		YYDollar = YYS[YYpt-7 : YYpt+1]
//line parser/grammar.y:107
		{
			YYVAL.Ast = &WhileStatement{Cond: YYDollar[3].Ast, Body: YYDollar[6].Ast}
		}
	case 43:
		YYDollar = YYS[YYpt-10 : YYpt+1]
//line parser/grammar.y:111
		{
			YYVAL.Ast = &FuncDecl{Name: YYDollar[2].String, Params: YYDollar[4].Params, ReturnType: YYDollar[7].Type, Body: YYDollar[9].Ast}
		}
	case 44:
		YYDollar = YYS[YYpt-0 : YYpt+1]
//line parser/grammar.y:115
		{
			YYVAL.Params = nil
		}
	case 46:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:120
		{
			YYVAL.Params = []Param{{Name: YYDollar[1].String, Type: YYDollar[3].Type}}
		}
	case 47:
		YYDollar = YYS[YYpt-5 : YYpt+1]
//line parser/grammar.y:121
		{
			YYVAL.Params = append(YYDollar[1].Params, Param{Name: YYDollar[3].String, Type: YYDollar[5].Type})
		}
	case 48:
		YYDollar = YYS[YYpt-2 : YYpt+1]
//line parser/grammar.y:125
		{
			YYVAL.Ast = &ReturnStmt{Expr: YYDollar[2].Ast}
		}
	case 49:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:126
		{
			YYVAL.Ast = &ReturnStmt{}
		}
	case 50:
		YYDollar = YYS[YYpt-0 : YYpt+1]
//line parser/grammar.y:130
		{
			YYVAL.Asts = nil
		}
	case 52:
		YYDollar = YYS[YYpt-1 : YYpt+1]
//line parser/grammar.y:135
		{
			YYVAL.Asts = []Ast{YYDollar[1].Ast}
		}
	case 53:
		YYDollar = YYS[YYpt-3 : YYpt+1]
//line parser/grammar.y:136
		{
			YYVAL.Asts = append(YYDollar[1].Asts, YYDollar[3].Ast)
		}
	}
	goto YYstack /* stack new state and value */
}
